### PR TITLE
Introduce App Blacklist

### PR DESCRIPTION
**Pull request by flyingrub**
Conflicts:
	app/src/main/java/org/holylobster/nuntius/Activity/SettingsActivity.java

App Blacklist improve

Conflicts:
	app/src/main/res/values/styles.xml

Add translatable string

Improve Style

Transaltion fix

_____________________
Need testing, i didn't install the desktop app yet...
(i will try it as soon as i can get a fedora running with optimus driver and 1920x1080 instead of 3200x1800)

### CODE REVIEW

**Comment by flyingrub** [comment]
preview

Would you like that i remove all the preinstalled app ?

**Comment by Kurtpenter** [comment]
Cool! My suggestions:
1) let's have a list of predefined blacklisted apps, maybe in a resource
file. Skipping preinstalled apps may not be correct in general, maybe I
have a preinstalled app which sends important notifications, right?
2) I'd prefer to show the name of the App and maybe the package in smaller
font below it... but we can improve gradually on this topic
3) how do you blacklist an app? I was thinking about a checkbox near the
name but maybe you have a better UI workflow in mind.

I'll try to merge it but I have some conflicts so I'll have to do it this
evening probably.

Bye,
Kurt

**Comment by flyingrub** [comment]
i just created a new branch with merge conflict resolved :)
1) Why would we need predefined blacklist ?
2) in fact, it's only with those preinstalled app with no name and no icon that it show the package name...
3) let's see the screenshoot below, there is a snackbar that pop up when an app is added or deleted (when you click on the item of the recyclerview) :




i use this lib : https://github.com/nispok/snackbar

**Comment by Kurtpenter** [comment]
On Mon, Mar 16, 2015 at 2:59 PM, Ronan Nello <notifications@github.com>
wrote:

> i just created a new branch with merge conflict resolved :)
> 1) Why would we need predefined blacklist ?
>
It is a way to avoid notifications from some system apps. I also saw some
other apps like Nuntius skip well known apps directly in the code because
they send useless notifications. But that was just an idea and we can add
it afterwards by making some apps blacklisted by default, we'll see how it
goes with what you've done. Maybe it is more than enough!

> 2) in fact, it's only with those preinstalled app with no name and no icon
> that it show the package name...
>
Ah, ok. In any case I do not think we can skip all these apps, maybe some
of them send important notifications despite the missing name or being
preinstalled.

> 3) let's see the screenshoot below, there is a snackbar that pop up when
> an app is added or deleted (when you click on the item of the recyclerview)
> :
>
Cool!

**Pull request closed without merging**
