### PR TITLE
Add some string translatable, material theme, prepare app blacklist

### PR DESCRIPTION
**Pull request by flyingrub**

### CODE REVIEW

**Comment by flyingrub** [comment]
i didn't tested it with the desktop, but there should be no problem i think.
perhaps in ther server class there is some improve to do?

**Comment by flyingrub** [comment]
there is still some bug:
* the blacklist view won't update with the sorted list.
* the server need more test.
i think those two problem are related to sharepreference wich won't update...

**Comment by nacho** [comment]
how about splitting this into several pull requests? this way we can start merging some of your patches :)

**Comment by flyingrub** [comment]
this one too

**Pull request closed without merging**
